### PR TITLE
Fix await consistent bug for replica node

### LINKED ISSUE #1: 【BUG】 recoveryTracker should overlap or follow on disk last VLSN of xxx recoveryFirst= xxx
When restart the replica node, the environment may start failed with the following error:

Environment invalid because of previous exception: (JE 7.3.7) 172.26.92.154_29917_1632321199655(-1):/home/disk1/gengjun/fe/meta/bdb recoveryTracker should overlap or follow on disk last VLSN of 1,754,423 recoveryFirst= 1,754,425 UNEXPECTED_STATE_FATAL: Unexpected internal state, unable to continue. Environment is invalid and must be closed.

To reproduce this bug:
1. Set the config of je.checkpointer.bytesInterval to a very tiny value, 2 for example.
2. restart the replica node frequently.

### PR DESCRIPTION
**Pull request by gengjun-git**
Fix #1 
Use a variable (replicaLatestVLSNSeq) to record the latest vlsn copied from master node. And wait for the replicaLatestVLSNSeq appeared in the vlsnIndex before completing the checkpoint.

### CODE REVIEW

File: src/com/sleepycat/je/rep/impl/node/Replay.java [hunk 1]
```diff
@@ -497,6 +497,7 @@ public void replayEntry(long startNs,
         final byte entryType = wireRecord.getEntryType();
 
         lastReplayedVLSN = wireRecord.getVLSN();
+        repImpl.getVLSNIndex().setReplicaLatestVLSNSeq(lastReplayedVLSN.getSequence());
```
Comment (lfoutz) [inline src/com/sleepycat/je/rep/impl/node/Replay.java]: You want to set the replicaLatestVLSNSeq in LogManager.java just below line 569 within the else statement.  The reason is that JE can transition from replica to master between setting it here and writing it to the logs, meaning you would have recorded a VLSN that was never made persistent.  The line in LogManager should be something like:

```
                 vlsn = params.repContext.getClientVLSN();
+                if (params.repContext.inReplicationStream()) {
+                    envImpl.setReplicaLatestVLSNSeq(vlsn);
+                }
```

Note for this to work you will have to add the function setReplicaLatestVLSNSeq in EnvironmentImpl, and overload it in RepImpl.

File: src/com/sleepycat/je/rep/vlsn/VLSNIndex.java [hunk 2]
```diff
@@ -472,6 +479,7 @@ public synchronized void initAsReplica() {
 
         putWaitVLSN = null;
         nextVLSNCounter = null;
+        replicaLatestVLSNSeq = VLSN.NULL_VLSN_SEQUENCE;
```
Comment (lfoutz) [inline src/com/sleepycat/je/rep/vlsn/VLSNIndex.java]: Here set replicaLatestVLSNSeq to VLSN.UNINITIALIZED_VLSN_SEQUENCE.  That way you can tell if this node is a replica or not.

File: src/com/sleepycat/je/rep/vlsn/VLSNIndex.java [hunk 3]
```diff
@@ -2064,12 +2080,6 @@ public boolean isFlushedToDisk() {
      * feeder waiting contract (VLSN N)
      */
     public void awaitConsistency() {
-
-        /* VLSNIndex is not initialized and in use yet, no need to wait. */
-        if (nextVLSNCounter == null) {
-            return;
-        }
-
```
Comment (lfoutz) [inline src/com/sleepycat/je/rep/vlsn/VLSNIndex.java:2072]: Leave this line in, because there is no point in waiting if the node has not yet been initiallized as a replica or a master.  But change it to something like:
```
         if (nextVLSNCounter == null && replicaLatestVLSNSeq == VLSN.NULL_VLSN_SEQUENCE) {
                return;
         }
```

**Review by lfoutz — APPROVED** [review]

**Comment by gengjun-git** [comment]
@lfoutz Thanks for review.
